from __future__ import annotations

from typing import Protocol

from alletra_onboard.domain.models import ArrayWorkItem, BrowserResultStatus, RunEvent, RunRecord
from alletra_onboard.domain.storage import ProvisioningIntent


class EventSink(Protocol):
    async def publish(self, event: RunEvent) -> None: ...


class RunStore(Protocol):
    def initialize(self) -> None: ...
    def upsert_run(self, run: RunRecord) -> None: ...
    def get_run(self, run_id: str) -> RunRecord | None: ...
    def list_runs(self) -> list[RunRecord]: ...
    def append_event(self, event: RunEvent) -> None: ...
    def list_events(self, run_id: str) -> list[RunEvent]: ...
    def save_work_item(self, run_id: str, item: ArrayWorkItem) -> None: ...
    def get_work_item(self, run_id: str) -> ArrayWorkItem | None: ...
    def save_provisioning_intent(self, run_id: str, intent: ProvisioningIntent) -> None: ...
    def get_provisioning_intent(self, run_id: str) -> ProvisioningIntent | None: ...


class CloudinitWizard(Protocol):
    async def run(self, item: ArrayWorkItem, run_id: str) -> BrowserResultStatus: ...


class DsccSetupWizard(Protocol):
    async def run(self, item: ArrayWorkItem, run_id: str) -> BrowserResultStatus: ...
